#loads data from tab-delimited .txt file
#data should contain raw transcript reads after Trinity assembly
library("edgeR")
library("dexus")
setwd("~/My Dropbox/HBOI/sponge NGS")

#Please pay no attention to this
#R Studio history follows, needs to be edited
col_names<-c("OC","UC","OD","UD")
col_names
colnames(reads)<-col_names
head(reads)
col_names<-c("OC_reads","UC_reads","OD_reads","UD_reads")
colnames(reads)<-col_names
head(reads)
fold_change<-reads$OC_reads/reads$UC_reads
head(fold_change)
class(reads)
reads<-rbind(reads,fold_change)
head(reads)
class(fold_change)
reads<-rbind(reads,(reads$OC_reads/reads$UC_reads))
head(Reads)
head(reads)
as.matrix(fold_change)
foldchangematrix<-as.matrix(fold_change)
head(fold_change)
head(foldchangematrix)
fold_change<-read$OD_reads/reads$UC_reads
fold_change<-reads$OD_reads/reads$UC_reads
foldchangematrix<-rbind(foldchangematrix,as.matrix(fold_change))
fold_change<-reads$OD_reads/reads$UC_reads
foldchangematrix<-as.matrix(fold_change)
fold_change<-reads$OC_reads/reads$UC_reads
foldchangematrix<-cbind(foldchangematrix,as.matrix(fold_change))
fold_change<-reads$UD_reads/reads$UC_reads
foldchangematrix<-cbind(foldchangematrix,as.matrix(fold_change))
col_names<-c("OD/UC","OC/UC","UD/UC")
colnames(foldchangematrix)<-col_names
head(foldchangematrix)
class(reads)
head(reads)
foldchangeframe<-data.frame(foldchangematrix)
head(foldchangeframe)
reads<-cbind(reads,foldchangeframe)
head(reads)
?sort
?order
install.packages("eeptools")
stulevel<-reads[order(reads$UD.UC),]
head(stulevel)
fold_change
stulevel1<-reads[order(reads$UD.UC),]
head(stulevel1)
stulevel1<-reads$UD.UC[order(reads$UD.UC),]
order<-reads$UD.UC
order1<-reads$UD.UC
stulevel<-order1[order(order1$UD.UC),]
head(order1)
order1<-as.matrix(reads$UD.UC)
reads_FC<-read.delim("General_expression_table.txt")
head(reads_FC)
colnames(reads_FC)<-reads_FC$Feature.ID
colname<-reads_FC$Feature.ID
colnames(reads_FC)<-colname
length(colname)
rownames(reads_FC)<-colname
head(reads_FC)
reads_FC<-reads_FC[,-1]
head(reads_FC)
OD_FC<-reads_FC[order(reads_FC$OD.UC),]
head(OD_FC)
OD_FC<-OD_FC[,-(1:6)]
head(OD_FC)
OD_FC<-reads_FC[order(reads_FC$OD.UC),]
OD_FC<-OD_FC[,-(1:5)]
head(OD_FC)
?summaryBy
??summaryBy
mean_OC<-mean(OD_FC$OC.UC)
OD_FC<-reads_FC[order(reads_FC$OD.UC),]
OD_FC<-OD_FC[,-(1:4)]
head(OD_FC)
OD_FC<-OD_FC[,-(2:3)]
head(OD_FC)
class(OD_FC)
OD_FC<-numeric(OD_FC)
OD_FC<-as.numeric(OD_FC)
class(OD_FC)
OD_mean<-mean(OD_FC)
OD_mean
OD_sd<-sd(OD_FC)
head(OD_FC)
head(reads_FC)
?plot
?barplot
?plot
plot(data$Feature.ID,reads_FC$OD)
head(reads)
hist(reads_FC$OC_reads)
class(reads_FC$OC_reads)
hist(OD_FC)
density(OD_FC)
d<-density(OD_FC)
plot(d)
head(reads_FC)
head(Reads)
head(reads)
d<-density(reads$UD.UC)
UD_density<-as.numeric(reads$UD.UC)
d<-density(UD_density)
class(UD_density)
plot(d)
reads<-reads(,-4:6)
head(reads)
reads<-reads[,-4:6]
reads<-reads[,-(4:6)]
head(reads)
reads<-data.frame(data[,c(14,25,36,47)])
col_names
col_names<-c("OC","UC","OD","UD")
head(reads)
head(data)
rownames(reads)<-data$Feature.ID
colnames(reads)<-col_names
head(reads)
reads_shift1<-reads$OC+1
reads_shift1<-data.frame(reads_shift1)
head(reads_shift1)
colnames(reads_shift1)<-"OC"
rownames(reads_shift1)<-data$Feature.ID
reads_shift1<-cbind(reads_shift1,reads$UC+1)
head(reads_shift1)
reads_shift1<-cbind(reads_shift1,reads$OD+1)
reads_shift1<-cbind(reads_shift1,reads$UD+1)
head(reads_shift1)
colnames(reads_shift1)<-col_names
head(reads_shift1)
reads_FC<-reads_shift1
reads_FC<-cbind(reads_FC,reads_FC$OC/reads_FC$UC)
head(reads_FC)
reads_FC<-cbind(reads_FC,reads_FC$OD/reads_FC$UC)
reads_FC<-cbind(reads_FC,reads_FC$UD/reads_FC$UC)
head(reads_FC)
col_names_FC<-col_names
col_names_FC<-c("OC","UC","OD","UD","OC_UC","OD_UC","UD_UC")
colnames(reads_FC)<-col_names
head(reads_FC)
col_names_FC<-c("OC","UC","OD","UD","OC.UC","OD.UC","UD.UC")
colnames(reads_FC)<-col_names_FC
head(reads_FC)
reads_FC_log2<-log(reads_FC[,5:7],2)
head(reads_FC_log2)
hist(reads_FC_log2)
hist(reads_FC_log2$OC.UC)
hist(reads_FC_log2$OD.UC)
hist(reads_FC_log2$UD.UC)
?hist
density(reads_FC_log2$UD.UC)
mean(reads_FC_log2$UD.UC)
sd(reads_FC_log2$UD.UC)
?heatmap
sort_FC_OC<-reads_FC_log2$OC.UC[order(OC.UC),]
sort_FC_OC<-reads_FC_log2[order(OC.UC),]
sort_FC_OC<-reads_FC_log2[order(reads_FC_log2$OC.UC),]
head(reads_FC_log2)
head(sort_FC_OC)
sort_FC_OD<-reads_FC_log2[order(reads_FC_log2$OD.UC),]
sort_FC_UD<-reads_FC_log2[order(reads_FC_log2$UD.UC),]
sorted<-sort_FC_OC$OC.UC
head(sorted)
sort_FC_OD_up<-sort_FC_OD[1:30,]
sort_FC_OD_down<-reads_FC_log2[order(-reads_FC_log2$OD.UC),]
head(sort_FC_OD_up)
head(sort_FC_OD_down)
sort_FC_OD_down<-sort_FC_OD_down[1:30,]
write.table(sort_FC_OD_down,"sort_FC_OD_down.txt",sep="\t")
write.table(sort_FC_OD_up,"sort_FC_OD_up.txt",sep="\t")
sort_FC_OC_up<-sort_FC_OC[1:30,]
sort_FC_UD_up<-sort_FC_UD[1:30,]
sort_FC_OC_down<-reads_FC_log2[order(-reads_FC_log2$OC.UC),]
sort_FC_UD_down<-reads_FC_log2[order(-reads_FC_log2$UD.UC),]
sort_FC_OC_down<-sort_FC_OD_down[1:30,]
sort_FC_UD_down<-sort_FC_OD_down[1:30,]
write.table(sort_FC_OC_down,"sort_FC_OC_down.txt",sep="\t")
write.table(sort_FC_OC_up,"sort_FC_OC_up.txt",sep="\t")
write.table(sort_FC_UD_down,"sort_FC_UD_down.txt",sep="\t")
write.table(sort_FC_UD_up,"sort_FC_UD_up.txt",sep="\t")
sort_FC_OD<-reads_FC_log2[order(reads_FC_log2$OD.UC),]
sort_FC_OC<-reads_FC_log2[order(reads_FC_log2$OC.UC),]
sort_FC_UD<-reads_FC_log2[order(reads_FC_log2$UD.UC),]
sort_FC_OD_up<-sort_FC_OD[1:50,]
sort_FC_OC_up<-sort_FC_OC[1:50,]
sort_FC_UD_up<-sort_FC_UD[1:50,]
sort_FC_OD_down<-reads_FC_log2[order(-reads_FC_log2$OD.UC),]
sort_FC_OC_down<-reads_FC_log2[order(-reads_FC_log2$OC.UC),]
sort_FC_UD_down<-reads_FC_log2[order(-reads_FC_log2$UD.UC),]
sort_FC_OD_down<-sort_FC_OD_down[1:50,]
sort_FC_OC_down<-sort_FC_OD_down[1:50,]
sort_FC_UD_down<-sort_FC_OD_down[1:50,]
write.table(sort_FC_OD_down,"sort_FC_OD_down.txt",sep="\t")
write.table(sort_FC_OD_up,"sort_FC_OD_up.txt",sep="\t")
write.table(sort_FC_UD_down,"sort_FC_UD_down.txt",sep="\t")
write.table(sort_FC_UD_up,"sort_FC_UD_up.txt",sep="\t")
write.table(sort_FC_OC_down,"sort_FC_OC_down.txt",sep="\t")
write.table(sort_FC_OC_up,"sort_FC_OC_up.txt",sep="\t")
sort_FC_OD<-reads_FC_log2[order(reads_FC_log2$OD.UC),]
sort_FC_OC<-reads_FC_log2[order(reads_FC_log2$OC.UC),]
sort_FC_UD<-reads_FC_log2[order(reads_FC_log2$UD.UC),]
sort_FC_OD_up<-sort_FC_OD[1:50,]
sort_FC_OC_up<-sort_FC_OC[1:50,]
sort_FC_UD_up<-sort_FC_UD[1:50,]
sort_FC_OD_down<-reads_FC_log2[order(-reads_FC_log2$OD.UC),]
sort_FC_OC_down<-reads_FC_log2[order(-reads_FC_log2$OC.UC),]
sort_FC_UD_down<-reads_FC_log2[order(-reads_FC_log2$UD.UC),]
sort_FC_OD_down<-sort_FC_OD_down[1:50,]
sort_FC_OC_down<-sort_FC_OC_down[1:50,]
sort_FC_UD_down<-sort_FC_OD_down[1:50,]
write.table(sort_FC_OD_down,"sort_FC_OD_down.txt",sep="\t")
write.table(sort_FC_OD_up,"sort_FC_OD_up.txt",sep="\t")
write.table(sort_FC_UD_down,"sort_FC_UD_down.txt",sep="\t")
write.table(sort_FC_UD_up,"sort_FC_UD_up.txt",sep="\t")
write.table(sort_FC_OC_down,"sort_FC_OC_down.txt",sep="\t")
write.table(sort_FC_OC_up,"sort_FC_OC_up.txt",sep="\t")
sort_FC_UD<-reads_FC_log2[order(reads_FC_log2$UD.UC),]
sort_FC_UD_down<-sort_FC_UD_down[1:50,]
write.table(sort_FC_UD_down,"sort_FC_UD_down.txt",sep="\t")
sort_FC_OD<-reads_FC_log2[order(reads_FC_log2$OD.UC),]
sort_FC_OC<-reads_FC_log2[order(reads_FC_log2$OC.UC),]
sort_FC_UD<-reads_FC_log2[order(reads_FC_log2$UD.UC),]
sort_FC_OD_up<-sort_FC_OD[1:50,]
sort_FC_OC_up<-sort_FC_OC[1:50,]
sort_FC_UD_up<-sort_FC_UD[1:50,]
sort_FC_OD_down<-reads_FC_log2[order(-reads_FC_log2$OD.UC),]
sort_FC_OC_down<-reads_FC_log2[order(-reads_FC_log2$OC.UC),]
sort_FC_UD_down<-reads_FC_log2[order(-reads_FC_log2$UD.UC),]
sort_FC_OD_down<-sort_FC_OD_down[1:50,]
sort_FC_OC_down<-sort_FC_OC_down[1:50,]
sort_FC_UD_down<-sort_FC_UD_down[1:50,]
write.table(sort_FC_OD_down,"sort_FC_OD_down.txt",sep="\t")
write.table(sort_FC_OD_up,"sort_FC_OD_up.txt",sep="\t")
write.table(sort_FC_UD_down,"sort_FC_UD_down.txt",sep="\t")
write.table(sort_FC_UD_up,"sort_FC_UD_up.txt",sep="\t")
write.table(sort_FC_OC_down,"sort_FC_OC_down.txt",sep="\t")
write.table(sort_FC_OC_up,"sort_FC_OC_up.txt",sep="\t")
reads_FC_log2_matrix<-as.matrix(reads_FC_log2)
heatmap(reads_FC_log2_matrix)
?topTable
?model.matrix
?heatmap
head(reads_FC_log2_matrix)
head(data$Feature.ID)
reads_FC_log2_matrix<-cbind(reads_FC_log2_matrix,data$Feature.ID)
head(data)
col_names<-colnames(data)
col_names
expressionvalues<-as.matrix(data[,c(1,15,26,37,48)])
head(expressionvalues)
heatmap(expressionvalues[1,],labCol=colnames(expressionvalues))
expressionvalues<-as.matrix(data[,c(15,26,37,48)])
head(expressionvalues)
heatmap(expressionvalues,labCol=colnames(expressionvalues))
?topTable
require(Biobase)
data(sample.ExpressionSet)
sample.ExpressionSet
exdat=sample.ExpressionSet
require(limma)
design1=model.matrix(~type,data=pData(exdat))
lm1=lmFit(exprs(exdat),design1)
lm1=eBayes(lm1)
geneID=rownames(topTable(lm1,coef=2,num=100,adjust="none",p.value=0.05))
length(geneID)
exdat2=exdat[geneID,]
require(Heatplus)
source("http://bioconductor.org/biocLite.R")
biocLite("ChromHeatMap")
biocLite("Heatplus")
require(Heatplus)
reg1=regHeatmap
reg1=regHeatmap(exprs(exdat))
plot(reg1)
reg2=regHeatmap(exprs(exdat2),legend2,col=heat.colors,breaks=-3.3)
reg2=regHeatmap(exprs(exdat2),legend=2,col=heat.colors,breaks=-3.3)
plot(reg2)
?heatmap.2
?gplots
biocLite("geneplotter")
?heatmap
x  <- as.matrix(mtcars)
rc <- rainbow(nrow(x), start = 0, end = .3)
cc <- rainbow(ncol(x), start = 0, end = .3)
hv <- heatmap(x, col = cm.colors(256), scale = "column",
RowSideColors = rc, ColSideColors = cc, margins = c(5,10),
xlab = "specification variables", ylab =  "Car Models",
main = "heatmap(<Mtcars data>, ..., scale = \"column\")")
head(mtcars)
reads<-data.matrix(data[,c(14,25,36,47)])
result<-dexus(reads)
informativeTranscripts<-INI(result,threshold=0.2)
transcripts<-as.data.frame(informativeTranscripts)
head(transcripts)
informativeTranscripts
reads<-data
class(data)
reads<-data.matrix(data)
result<-dexus(reads,nclasses=3,alphalnit=c(1,1,1))
head(data)
col_names
reads<-data.matrix(data[,c(14,25,36,47)])
result<-dexus(reads,nclasses=3,alphaInit=c(1,1,1))
informativeTranscripts<-INI(result,threshold=0.2)
plot(sort(result),idx=1:10)
?dexus
plot(result)
plot(sort(result),idx=1:10)
plot(sort(result))
plot(sort(result),idx=1:10)
head(result)
head(informativeTranscripts)
